# Files with dependencies are set up to be linted by the verilator CI job
groups:
  - top: Basic_AXI_SPI
    files: 
      - src/Basic_AXI_SPI.v
      - src/BasicSPI.v
  - top: SPIController
    files: 
      - src/SPIController.v
      - src/SPITransmitter.v
