import random


class DummyData:
    def __init__(self, num_bytes=0, word_width=4):
        self.num_bytes = num_bytes
        self._array = []
        self.generate_test_array(num_bytes)
        self.is_little_endian = True
        self.word_width = word_width

    def generate_test_array(self, num_bytes):
        self._array = []
        self.num_bytes = num_bytes

        for _ in range(num_bytes):
            self._array.append(random.randrange(256))

    def get_test_array(self):
        return self._array

    def get_test_number(self):
        number = 0
        if self.is_little_endian:
            for i in self._array[::-1]:
                number = (number << 8) + i
        else:
            for i in self._array:
                number = (number << 8) + i

        return number

    def get_test_number_word(self, address, width=-1):
        if width == -1:
            width = self.word_width

        number = 0
        start = address
        end = address + width
        if self.is_little_endian:
            for i in self._array[end - 1 :: -1][: width]:
                number = (number << 8) + i
        else:
            for i in self._array[start:end]:
                number = (number << 8) + i
        return number


    # swap_endian_32 was mainly generated by claude code
    def swap_endian_32(data):
        """
        Convert a byte array between big-endian and little-endian,
        assuming a word width of 4 bytes.

        Full 4-byte words are reversed. Any trailing bytes that don't
        complete a full word are left unchanged (in original order).
        """
        result = []
        full_words_len = (len(data) // 4) * 4

        # Swap complete 4-byte words
        for i in range(0, full_words_len, 4):
            word = data[i:i+4]
            result.extend(reversed(word))

        # append the remaining partial word
        result.extend(reversed(data[full_words_len:]))

        return result
